spring.application.name=exammanagement
spring.datasource.url=jdbc:postgresql://localhost:5432/exam-management
spring.datasource.username=postgres
spring.datasource.password=3378
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

admin.username=admin
admin.password=admin
